name: Python Linting
description: Lint a Python project.
inputs:
  python-version:
    default: '3.10'
  package-path:
    default: src
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v2
      shell: 'bash'
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python-version }}
      shell: 'bash'
    - name: Install dependencies
      run: |
        pip install poetry
        poetry install
      shell: 'bash'
    - name: Run Pylint
      run: poetry run pylint ${{ inputs.package-path }}
      shell: 'bash'
